Renamed files

diff --git a/bin/play-deploy b/bin/play-deploy
--- a/bin/play-deploy
+++ b/bin/play-deploy
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+SCRIPT_DIR=`dirname $0`
+HELPER_DIR="$SCRIPT_DIR/../helper"
+
+if [ ! -f "conf/application.conf" ]; then
+  echo "Current directory does not appear to be a play app!"
+  exit 1
+fi
+
 CONFIG_FILE="conf/deploy.conf"
 
 if [ ! -f $CONFIG_FILE ]; then
@@ -59,15 +67,24 @@ if [ ! $? -eq 0 ]; then
   exit 1
 fi
 
-
-# time to rsync staged jars (include deletes of jars that don't match source)
+# rsync staged jars (include deletes of jars that don't match source)
 rsync --progress -avrt -d --delete -e "ssh -i $deploy_pem" $stage_dir/ $deploy_user@$deploy_host:$deploy_dir/play-$DEPLOYED_AT/
 if [ ! $? -eq 0 ]; then
   echo "rsync failed!"
   exit 1
 fi
 
-echo "Successfully deployed new application build!"
+echo "Successfully rsynced application libraries!"
+
+# rsync helper run/start/stop scripts
+rsync --progress -avrt -e "ssh -i $deploy_pem" $HELPER_DIR/* $deploy_user@$deploy_host:$deploy_dir/
+if [ ! $? -eq 0 ]; then
+  echo "rsync failed!"
+  exit 1
+fi
+
+echo "Successfully rsynced helper run/start/stop scripts!"
+
 
 # let user decide if remote app should be restarted?
 read -p "Restart play application on remote host (y/n)? " choice
@@ -85,13 +102,13 @@ SCRIPT_TO_RUN=/tmp/deploy-on-remote.sh
 cat <<EOF > $SCRIPT_TO_RUN
  STDOUT_FILE=$deploy_dir/logs/stdout.log
 
- $deploy_dir/play-stop.sh
+ $deploy_dir/play-stop
  if [ ! \$? -eq 0 ]; then
    echo "unable to stop app; skipping restart"
    exit 1
  fi
 
- $deploy_dir/play-start.sh
+ $deploy_dir/play-start
 EOF
 
 ssh -i $deploy_pem $deploy_user@$deploy_host '/bin/bash' < $SCRIPT_TO_RUN
